[Component]
    Name = "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.recommendationservice"
    Version = "1.2.2"
    ChartName = "chart/recommendationservice"
    DockerRepo = "quay.io/hipsterstore/recommendationservice"
    GitUrl = "https://github.com/ortelius/store-recommendationservice"
    HelmChart = "GLOBAL.HelmChart"
    Applications = [
        "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.Webstore;July 4th Sale;1.2.9.1"
    ]