apiVersion: v1
kind: Service
metadata:
  name: {{ include "recommendationservice.name" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "recommendationservice.name" . }}
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080